#
#spring:
#  profiles:
#    active:
#      on-profile: local
#  datasource:
#    hikari:
#      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#      username: sa
#      password:
#      driver-class-name: org.h2.Driver
#
#---
#spring:
#  profiles:
#    active:
#      on-profile: mysql
#  datasource:
#    hikari:
#      jdbc-url: jdbc:mysql://localhost:3306/spring-batch?useUnicode=true&characterEncoding=utf8
#      username: root
#      password: 12341234
#      driver-class-name: com.mysql.jdbc.Driver
#  batch:
#    jdbc:
#      initialize-schema: always