spring:
  datasource:
    username: wegoolid
    password: password
    url: jdbc:mysql://localhost:3306/wegooli?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: MYSQL
    show-sql: true
    properties:
      hibernate.globally_quoted_identifiers: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate:
        connection:
          charSet: UTF-8
    defer-datasource-initialization: true
  batch:
    job:
      enabled: false # 자동실행
    jdbc:
      initialize-schema: always
  h2:
    console:
      enabled: true
